<?php
/* @var $this ProjectTeachingController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
    '教改项目',
);

?>
<div style="position:relative">
    <img src="images/lang1.jpg" alt="" />
    <div style="position:absolute;z-indent:2;left:0;top:0;">
        <br>
        <h2>教改项目</h2>
    </div>
</div>
<br/><br/>
<table class="table table-hover">
    <caption>各级教改项目19项，其中部省级以上的教改项目有7项，校级12项，以下列举的是部省级以上的教改项目。</caption>
    <thead>
    <tr>
        <th>序号</th>
        <th>项目名称</th>
        <th>项目来源</th>
        <th>负责人</th>
        <th>起止时间</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>1</td>
        <td>国内知名品牌专业通信工程的建设与实践</td>
        <th>教育部</th>
        <th>毛玉明</th>
        <th>2004</th>
    </tr>
    <tr>
        <td>2</td>
        <td>电子信息类专业专业课双语教学理论与实践探索</td>
        <th>教育部</th>
        <th>段景山</th>
        <th>2003</th>
    </tr>
    <tr>
        <td>3</td>
        <td>通信信息人才培养基地的建设</td>
        <th>教育部</th>
        <th>主研</th>
        <th>2001</th>
    </tr>
    <tr>
        <td>4</td>
        <td>网络工程第二特色专业建设</td>
        <th>教育部</th>
        <th>负责、主研</th>
        <th>2008</th>
    </tr>
    <tr>
        <td>5</td>
        <td>接入网技术课程建设与高水平教学队伍的培养</td>
        <th>教育部</th>
        <th>负责、主研</th>
        <th>2005-2008</th>
    </tr>
    <tr>
        <td>6</td>
        <td>网络设备原型实验平台建设</td>
        <th>教育部</th>
        <th>负责、主研</th>
        <th>2005-2008</th>
    </tr>
    <tr>
        <td>7</td>
        <td>国内知名品牌专业通信工程的建设与实践</td>
        <th>教育部</th>
        <th>负责、主研</th>
        <th>2005-2008</th>
    </tr>
    <tr>
        <td>8</td>
        <td>通信工程专业综合改革子项目：通信与信息系统实验教学示范中心</td>
        <th>四川省</th>
        <th>毛玉明</th>
        <th>2011</th>
    </tr>
    <tr>
        <td>9</td>
        <td>通信工程专业综合改革子项目：实验教学方法和手段研究与改革</td>
        <th>四川省</th>
        <th>段景山</th>
        <th>2011</th>
    </tr>
    <tr>
        <td>10</td>
        <td>网络工程专业综合改革子项目：网络工程特色专业</td>
        <th>四川省</th>
        <th>毛玉明</th>
        <th>2011</th>
    </tr>
    <tr>
        <td>11</td>
        <td>网络工程专业综合改革子项目：网络工程课程体系与课程内容建设</td>
        <th>四川省</th>
        <th>马立香</th>
        <th>2011</th>
    </tr>
    <tr>
        <td>12</td>
        <td>网络工程专业综合改革子项目：网络工程本科人才培养模式研究与改革</td>
        <th>四川省</th>
        <th>段景山</th>
        <th>2011</th>
    </tr>
    <tr>
        <td>13</td>
        <td>深化基于“四个融合”的高质量通信人才培养模式改革</td>
        <th>学校</th>
        <th>饶云江</th>
        <th>2013</th>
    </tr>
    <tr>
        <td>14</td>
        <td>打造通信大类专业特色课程体系，提高学生专业认同度研究与实践</td>
        <th>学校</th>
        <th>张进</th>
        <th>2013</th>
    </tr>
    <tr>
        <td>15</td>
        <td>2013年第一期本科教学实验室建设：WLAN实验室升级换代</td>
        <th>学校</th>
        <th>段景山</th>
        <th>2013</th>
    </tr>
    <tr>
        <td>16</td>
        <td>2011年“教师实验教学研究支持计划：基于成绩管理的软件基础技术设计</td>
        <th>学校</th>
        <th>段景山</th>
        <th>2011</th>
    </tr>
    <tr>
        <td>17</td>
        <td>2011年“教师实验教学研究支持计划：基于三层结构的通信协议设计</td>
        <th>学校</th>
        <th>段景山</th>
        <th>2011</th>
    </tr>
    <tr>
        <td>18</td>
        <td>2011年“教师实验教学研究支持计划：基于OPNET的SDH传输网与业务模型设计</td>
        <th>学校</th>
        <th>刘强</th>
        <th>2011</th>
    </tr>
    <tr>
        <td>19</td>
        <td>2011年“教师实验教学研究支持计划：用户接入控制实验系统设计与实现</td>
        <th>学校</th>
        <th>马立香</th>
        <th>2011</th>
    </tr>
    <tr>
        <td>20</td>
        <td>2011年“教师实验教学研究支持计划：有、无线局域网综合组网设计实现与协议分析</td>
        <th>学校</th>
        <th>韦云凯</th>
        <th>2011</th>
    </tr>
    <tr>
        <td>21</td>
        <td>2011年“教师实验教学研究支持计划：链路可靠传输协议设计</td>
        <th>学校</th>
        <th>毛玉明</th>
        <th>2011</th>
    </tr>
    <tr>
        <td>22</td>
        <td>2011年“教师实验教学研究支持计划：中等规模企业级IP网络系统设计</td>
        <th>学校</th>
        <th>吴凡、张科</th>
        <th>2011</th>
    </tr>
    <tr>
        <td>23</td>
        <td>2011年“教师实验教学研究支持计划：多媒体实时通信综合实验设计</td>
        <th>学校</th>
        <th>李龙江</th>
        <th>2011</th>
    </tr>
    </tbody>
</table>
<hr/>